-- Fondasi vendor: kode referral yang tidak bisa bentrok, identitas vendor,
-- dan pencatatan kunjungan.

-- ── 1. Kode referral wajib unik ────────────────────────────────────────────
-- LoginPage membuat kode sebagai nama depan + 3 angka acak tanpa cek tabrakan.
-- Kalau dua akun sampai punya kode sama, create-transaction.js mencarinya
-- dengan .maybeSingle() -- yang error saat dapat lebih dari satu baris. Kode
-- itu lalu ditolak checkout, jadi DUA vendor rusak sekaligus tanpa pesan apa
-- pun. Untuk kode yang sudah tercetak di brosur, itu tidak bisa diperbaiki
-- diam-diam.
--
-- Kalau perintah ini gagal, berarti sudah ada duplikat. Cari dengan:
--   select referral_code, count(*) from profiles
--   where referral_code is not null group by 1 having count(*) > 1;
create unique index if not exists profiles_referral_code_key
  on public.profiles (upper(referral_code))
  where referral_code is not null;

-- ── 2. Identitas vendor ────────────────────────────────────────────────────
-- Vendor tetap pengguna biasa: satu baris di sini menempel ke profiles, jadi
-- ia mewarisi kode referral, dompet, komisi, dan penarikan yang sudah jalan.
create table if not exists public.vendors (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null unique references public.profiles(id) on delete cascade,
  slug        text not null unique,
  name        text not null,
  category    text not null,
  city        text,
  tagline     text,
  description text,
  logo_url    text,
  cover_url   text,
  gallery     jsonb not null default '[]'::jsonb,
  whatsapp    text,
  instagram   text,
  website     text,
  price_from  integer,
  price_to    integer,
  verified    boolean not null default false,
  -- Sengaja default false: vendor setengah jadi tidak boleh tayang hanya
  -- karena barisnya sudah dibuat.
  visible     boolean not null default false,
  created_at  timestamptz not null default now()
);

alter table public.vendors
  drop constraint if exists vendors_category_check;
alter table public.vendors
  add constraint vendors_category_check check (category in (
    'Venue', 'Fotografer', 'Wedding Organizer', 'MUA',
    'Katering', 'Dekorasi', 'Busana', 'Hiburan'
  ));

create index if not exists vendors_visible_idx on public.vendors (visible, category);

alter table public.vendors enable row level security;

drop policy if exists "Public reads visible vendors" on public.vendors;
create policy "Public reads visible vendors" on public.vendors
  for select using (visible = true);

drop policy if exists "Vendor reads own row" on public.vendors;
create policy "Vendor reads own row" on public.vendors
  for select using (user_id = auth.uid());

-- Tidak ada policy UPDATE untuk vendor. Kontennya diurus admin, sesuai model
-- yang dipilih. Menambahkannya nanti cukup satu policy -- tapi kalau dibuka
-- sekarang, vendor juga bisa menyetel verified-nya sendiri lewat API.
drop policy if exists "Admins manage vendors" on public.vendors;
create policy "Admins manage vendors" on public.vendors
  for all using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  ) with check (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- ── 3. Kunjungan & klik ────────────────────────────────────────────────────
-- Statistik yang diminta vendor: berapa yang datang, berapa yang klik WA.
-- Dibuat sekarang, bukan nanti, karena trafik hari-hari pertama vendor
-- pertama tidak bisa diambil ulang kalau pencatatannya menyusul.
--
-- Angka ini bisa digelembungkan dari browser, dan itu memang dibiarkan: ia
-- tidak menyentuh uang sama sekali. Komisi hanya lahir dari transaksi lunas.
create table if not exists public.vendor_events (
  id         bigint generated by default as identity primary key,
  vendor_id  uuid not null references public.vendors(id) on delete cascade,
  kind       text not null check (kind in ('view', 'wa_click', 'code_copy', 'catalog_click')),
  created_at timestamptz not null default now()
);

create index if not exists vendor_events_vendor_idx
  on public.vendor_events (vendor_id, kind, created_at desc);

alter table public.vendor_events enable row level security;

-- Siapa pun boleh mencatat (pengunjung tidak login), tapi tidak boleh membaca.
drop policy if exists "Anyone logs vendor events" on public.vendor_events;
create policy "Anyone logs vendor events" on public.vendor_events
  for insert with check (true);

drop policy if exists "Vendor reads own events" on public.vendor_events;
create policy "Vendor reads own events" on public.vendor_events
  for select using (
    exists (select 1 from public.vendors v where v.id = vendor_id and v.user_id = auth.uid())
  );

drop policy if exists "Admins read vendor events" on public.vendor_events;
create policy "Admins read vendor events" on public.vendor_events
  for select using (
    exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

-- ── 4. Pembacaan publik halaman vendor ─────────────────────────────────────
-- Halaman vendor harus menampilkan kode referralnya, dan kode itu ada di
-- profiles -- tabel yang tidak boleh dibaca publik. Jadi jalurnya lewat satu
-- fungsi security definer, pola yang sama dengan validate_voucher: ia hanya
-- membocorkan satu kolom, dan hanya untuk vendor yang memang sudah tayang.
create or replace function public.get_vendor_by_slug(p_slug text)
returns table (
  id uuid, slug text, name text, category text, city text, tagline text,
  description text, logo_url text, cover_url text, gallery jsonb,
  whatsapp text, instagram text, website text,
  price_from integer, price_to integer, verified boolean, referral_code text
)
language sql
security definer
set search_path = public
as $$
  select v.id, v.slug, v.name, v.category, v.city, v.tagline,
         v.description, v.logo_url, v.cover_url, v.gallery,
         v.whatsapp, v.instagram, v.website,
         v.price_from, v.price_to, v.verified, p.referral_code
  from vendors v
  join profiles p on p.id = v.user_id
  where lower(v.slug) = lower(p_slug) and v.visible = true;
$$;
grant execute on function public.get_vendor_by_slug(text) to anon, authenticated;
