-- ============================================================================
-- Move pricing & vouchers to the database (so the payment server can trust them)
-- ============================================================================
-- Pricing and vouchers used to live only in browser localStorage, so the
-- Midtrans serverless functions couldn't read them and had to hardcode prices
-- and ignore vouchers. This moves both into Postgres as the source of truth:
--   * server computes the authoritative price + discount,
--   * admin edits persist for everyone (not just their browser),
--   * client reads the same numbers it will be charged.
-- ============================================================================


-- ── 1. pricing table ────────────────────────────────────────────────────────
create table if not exists pricing (
  category   text primary key,
  price      integer not null check (price >= 0),
  updated_at timestamptz default now()
);

insert into pricing (category, price) values
  ('Special', 99000), ('Adat', 110000), ('Motion', 140000), ('Luxury', 175000)
on conflict (category) do nothing;

alter table pricing enable row level security;

drop policy if exists "Public can read pricing" on pricing;
create policy "Public can read pricing" on pricing for select using (true);

drop policy if exists "Admins manage pricing" on pricing;
create policy "Admins manage pricing" on pricing for all
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'));


-- ── 2. vouchers table ────────────────────────────────────────────────────────
create table if not exists vouchers (
  id         bigint generated by default as identity primary key,
  code       text unique not null,
  type       text not null check (type in ('percent', 'flat')),
  discount   integer not null check (discount >= 0),
  max_use    integer not null default 100,
  used       integer not null default 0,
  created_at timestamptz default now()
);

insert into vouchers (code, type, discount, max_use, used) values
  ('HAPPYWEDDING', 'percent', 10, 100, 0),
  ('DISKON50', 'flat', 50000, 50, 0)
on conflict (code) do nothing;

alter table vouchers enable row level security;

-- No public SELECT — we don't want to leak the full list of promo codes.
-- Clients validate a single code through validate_voucher() below. The payment
-- server reads this table directly via the service role.
drop policy if exists "Admins manage vouchers" on vouchers;
create policy "Admins manage vouchers" on vouchers for all
  using (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from profiles p where p.id = auth.uid() and p.role = 'admin'));


-- ── 3. transactions: remember what discount was applied ──────────────────────
alter table transactions add column if not exists voucher_code   text;
alter table transactions add column if not exists discount_amount integer default 0;
alter table transactions add column if not exists referrer_id     uuid;


-- ── 4. RPCs ──────────────────────────────────────────────────────────────────
-- Validate a single voucher code without exposing the whole table. Returns the
-- code's terms only if it still has quota left.
create or replace function validate_voucher(p_code text)
returns table (code text, type text, discount integer)
language sql
stable
security definer
set search_path = public
as $$
  select v.code, v.type, v.discount
  from vouchers v
  where upper(v.code) = upper(p_code)
    and v.used < v.max_use;
$$;
grant execute on function validate_voucher(text) to anon, authenticated;

-- Look up a referrer by their referral code without exposing profiles. Excludes
-- the caller so nobody can use their own code.
create or replace function find_referrer_by_code(p_code text)
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select id from profiles
  where referral_code = p_code
    and id <> coalesce(auth.uid(), '00000000-0000-0000-0000-000000000000'::uuid)
  limit 1;
$$;
grant execute on function find_referrer_by_code(text) to anon, authenticated;

-- Atomic voucher-usage increment (called by the payment webhook on success).
create or replace function increment_voucher_usage(p_code text)
returns void
language sql
security definer
set search_path = public
as $$
  update vouchers set used = used + 1 where upper(code) = upper(p_code);
$$;
grant execute on function increment_voucher_usage(text) to authenticated, anon;
